".pyenv":
    type: "archive"
    url: "https://github.com/pyenv/pyenv/archive/refs/tags/{{ .pyenv_version }}.tar.gz"
    exact: false
    stripComponents: 1
".pyenv/plugins/pyenv-virtualenv":
    type: "git-repo"
    url: "https://github.com/pyenv/pyenv-virtualenv.git"
    refreshPeriod: "168h"
"bin/":
    type: "archive"
    url: "{{ .lazygit_base_url }}/v{{ .lazygit_version }}/lazygit_{{ .lazygit_version }}_{{ .chezmoi.os }}_{{ .chezmoi.arch | replace "amd64" "x86_64" }}.tar.gz"
    include: 
      - "lazygit"
"bin/":
    type: "archive"
    url: "{{ .doggo_base_url }}/v{{ .doggo_version }}/doggo_{{ .doggo_version }}_{{ .chezmoi.os }}_{{ . chezmoi.arch | replace "amd64" "x86_64" }}.tar.gz"
    include: 
      - "doggo"
".tools/nvim":
    type: "archive"
    url: "https://github.com/neovim/neovim/releases/download/v{{ .nvim_version }}/nvim-{{ .chezmoi.os | replace "darwin" "macos" }}-{{- .chezmoi.arch | replace "amd64" "x86_64" -}}.tar.gz"
    exact: true
    stripComponents: 1
    refreshPeriod: "168h"
".tools/npm":
    type: "archive"
    url: "https://nodejs.org/dist/{{ .nodejs_version }}/node-{{ .nodejs_version }}-{{ .chezmoi.os }}-{{ .chezmoi.arch | replace "amd64" "x64" }}.tar.gz"
    exact: true
    stripComponents: 1
    refreshPeriod: "168h"
