".pyenv":
    type: "archive"
    url: "https://github.com/pyenv/pyenv/archive/refs/tags/{{ .pyenv_version }}.tar.gz"
    exact: false
    stripComponents: 1
".pyenv/plugins/pyenv-virtualenv":
    type: "git-repo"
    url: "https://github.com/pyenv/pyenv-virtualenv.git"
    refreshPeriod: "168h"
"bin/":
    type: "archive"
    url: "{{ .lazygit_base_url }}/v{{ .lazygit_version }}/lazygit_{{ .lazygit_version }}_{{ .chezmoi.os }}_{{ .chezmoi.arch | replace "amd64" "x86_64" }}.tar.gz"
    include: 
      - "lazygit"
