# renovate: datasource=github-tags depName=pyenv/pyenv
pyenv_version: "v2.6.10"
# renovate: datasource=golang-version depName=go
go_version: "1.25.0"
# renovate: datasource=github-tags depName=jesseduffield/lazygit
lazygit_version: "0.54.2"
lazygit_base_url: "https://github.com/jesseduffield/lazygit/releases/download/"
# renovate: datasource=github-tags depName=neovim/neovim
nvim_version: "0.11.3"
# renovate: datasource=github-tags depName=nodejs/node
nodejs_version: "v24.7.0"
